# Generated by Django 5.0 on 2024-01-03 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain letters, numbers, or special characters (_.).', regex='^[a-zA-Z0-9_\\.\\-]{1,20}'), django.core.validators.MinLengthValidator(1, 'Username must be at least 1 character.'), django.core.validators.MaxLengthValidator(20, 'Username cannot be more than 20 characters.')]),
        ),
    ]
