# Generated by Django 5.0 on 2024-01-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
