# Generated by Django 5.0 on 2024-01-05 19:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[api.models.is_valid_file]),
        ),
    ]
