# Generated by Django 5.0 on 2024-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='origin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
