# Generated by Django 5.0 on 2024-01-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_file_origin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
