# Generated by Django 5.0 on 2024-01-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
