# Generated by Django 5.0.1 on 2024-02-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='aws_tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
