# Generated by Django 5.0.1 on 2024-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='aws_feelings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
